# Generated by Django 4.1.12 on 2023-10-11 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sxt2023_api", "0001_initial"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sxt2023_api.brand",
            ),
        ),
    ]
