# Generated by Django 5.2.7 on 2025-11-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_collation="case_insensitive",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
