# Generated by Django 4.1.12 on 2023-10-11 17:43

import uuid

import django.db.models.deletion
import psqlextra.manager.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("slug", models.CharField(max_length=256, unique=True)),
                (
                    "postal_address",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("maps_link", models.URLField(blank=True, null=True)),
                ("tree_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("tree_description", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sxt2023_api.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name="visit",
            constraint=models.UniqueConstraint(
                fields=("brand", "user"), name="one_visit_per_brand_and_user"
            ),
        ),
    ]
