# Generated by Django 5.2.7 on 2025-11-05 20:50

import django.db.models.deletion
import psqlextra.manager.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sxt2023_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreePageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tree_id", models.UUIDField()),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sxt2023_api.brand",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
